# there are 3 stages, 
# install that creates installs the dependencies and saves the artifacts, 
# lint that runs the linters,
# and test that runs the tests of the server

stages:
    - install
    - lint
    - test

install:
    stage: install
    image: node:10.16-alpine
    script:
        - cd ./client
        - npm ci
        - cd ..
        - cd ./server
        - npm ci
    artifacts:
        name: "artifacts"
        untracked: true
        expire_in: 30 mins 
        paths:
            - client/node_modules 
            - server/node_modules

lint:
    image: node:10.16-alpine
    stage: lint
    script:
        - cd ./client
        - npm run eslint
        - cd ..
        - cd ./server
        - npm run eslint

test:
    image: node:10.16-alpine
    stage: test
    script:
        - cd ./server
        - npm run test