stages:
    - install
    - lint
    - test
install:
    stage: install
    script:
        - npm install
    artifacts:
        name: "artifacts"
        untracked: true
        expire_in: 30 mins 
        paths:
            - .npm/
            - node_modules 
lint:
    stage: lint
    script:
        - cd ./client
        - npm run eslint
        - cd ..
        - cd ./server
        - npm run eslint

test:
    stage: test
    script:
        - cd ./server
        - npm run test